--GROUP BY / HAVING
-- GROUP BY : 그룹함수에 대해서 컬럼을 그룹으로 묶고자 할 때
SELECT DEPT_CODE, SUM(SALARY)
FROM EMPLOYEE; 

SELECT DEPT_CODE, SUM(SALARY)
FROM EMPLOYEE
GROUP BY DEPT_CODE
ORDER BY DEPT_CODE;

-- EMPLOYEE테이블에서 부서 코드 별 그룹을 지정하여 
-- 부서코드, 그룹별 급여 합계, 그룹별 급여 평균, 인원 수 조회(부서코드 순 정렬)
SELECT DEPT_CODE, SUM(SALARY), AVG(SALARY), COUNT(*)
FROM EMPLOYEE
GROUP BY DEPT_CODE
ORDER BY DEPT_CODE;
-- EMPLOYEE 테이블에서 부서코드와 보너스를 받는 사원 수 조회 (부서코드 순)
SELECT DEPT_CODE, COUNT(BONUS)
FROM EMPLOYEE
GROUP BY DEPT_CODE
ORDER BY DEPT_CODE;
-- EMPLOYEE 테이블에서 직급코드와 보너스를 받는 사원 수 조회 (직급코드 순)
-- COUNT가 0인 직급코드는 제외
SELECT JOB_CODE, COUNT(BONUS)
FROM EMPLOYEE
WHERE BONUS IS NOT NULL
GROUP BY JOB_CODE
ORDER BY JOB_CODE;


-- EMPLOYEE테이블에서 성별과 성별 별 급여 평균, 급여합계, 인원 수 조회
SELECT DECODE(SUBSTR(INSTR(EMP_NO, '-')+1, 1), 1, '남', '여') 성별,
        AVG(SALARY) "급여평균", SUM(SALARY) "급여합계", COUNT(*) "인원수"
FROM EMPLOYEE
GROUP BY SUBSTR(INSTR(EMP_NO, '-')+1, 1)
ORDER BY "인원수" DESC;


-- 부서코드 별로 같은 직급인 사원의 급여 합계
SELECT DEPT_CODE, JOB_CODE, SUM(SALARY)
FROM EMPLOYEE
GROUP BY DEPT_CODE, JOB_CODE
ORDER BY DEPT_CODE;

-- HAVING : 그룹함수에 대한 조건 설정
-- 부서코드와 급여 3000000 이상인 직원의 그룹별 평균 급여 조회

SELECT DEPT_CODE, AVG(SALARY)
FROM EMPLOYEE
WHERE SALARY >= 3000000
GROUP BY DEPT_CODE;

-- 부서코드와 급여 평균이 3000000 이상인 그룹 조회
SELECT DEPT_CODE, AVG(SALARY)
FROM EMPLOYEE
GROUP BY DEPT_CODE
HAVING AVG(SALARY) >= 3000000;

-- 부서별 그룹의 급여 합계 중 9백만을 초과하는 부서코드, 급여합계 조회
SELECT DEPT_CODE, SUM(SALARY)
FROM EMPLOYEE
GROUP BY DEPT_CODE
HAVING SUM(SALARY) > 9000000;

-- 집합 연산자
-- UNION : 합집합
-- INTERSECT : 교집합
-- UNION ALL : 합집합 + 교집합
-- MINUS : 차집합

-- DEPT_CODE가 D5인 사원의 사번, 이름, 부서코드, 급여 조회
SELECT EMP_ID, EMP_NAME, DEPT_CODE, SALARY
FROM EMPLOYEE
WHERE DEPT_CODE = 'D5';
-- 급여가 300만을 초과하는 사원의 사번, 이름, 부서코드, 급여 조회
SELECT EMP_ID, EMP_NAME, DEPT_CODE, SALARY
FROM EMPLOYEE
WHERE SALARY > 3000000;

-- UNION = OR
SELECT EMP_ID, EMP_NAME, DEPT_CODE, SALARY
FROM EMPLOYEE
WHERE DEPT_CODE = 'D5'
UNION
SELECT EMP_ID, EMP_NAME, DEPT_CODE, SALARY
FROM EMPLOYEE
WHERE SALARY > 3000000;

-- INTERSECT = AND
SELECT EMP_ID, EMP_NAME, DEPT_CODE, SALARY
FROM EMPLOYEE
WHERE DEPT_CODE = 'D5'
INTERSECT
SELECT EMP_ID, EMP_NAME, DEPT_CODE, SALARY
FROM EMPLOYEE
WHERE SALARY > 3000000;

-- UNION ALL
SELECT EMP_ID, EMP_NAME, DEPT_CODE, SALARY
FROM EMPLOYEE
WHERE DEPT_CODE = 'D5'
UNION ALL
SELECT EMP_ID, EMP_NAME, DEPT_CODE, SALARY
FROM EMPLOYEE
WHERE SALARY > 3000000;


-- MINUS
SELECT EMP_ID, EMP_NAME, DEPT_CODE, SALARY
FROM EMPLOYEE
WHERE DEPT_CODE = 'D5'
MINUS
SELECT EMP_ID, EMP_NAME, DEPT_CODE, SALARY
FROM EMPLOYEE
WHERE SALARY > 3000000;
