SELECT DEPT_ID, DEPT_TITLE
FROM DEPARTMENT;

-- 내부 조인 (INNER JOIN) : 컬럼의 값이 일치하는 행들만 조회
-- 오라클 전용 구문, ANSI 구문
-- 사번, 사원 명, 부서코드, 부서 명 조회

SELECT EMP_ID, EMP_NAME, DEPT_CODE, DEPT_TITLE
FROM EMPLOYEE, DEPARTMENT
WHERE DEPT_ID = DEPT_CODE; -- 오라클 전용 구문

-- 사번, 사원 명, 직급코드, 직급명
SELECT EMP_ID, EMP_NAME, J.JOB_CODE, JOB_NAME
FROM EMPLOYEE E, JOB J
WHERE E.JOB_CODE = J.JOB_CODE;



-- ANSI 구문
-- 사번, 사원 명, 부서코드, 부서명 조회(컬렴명이 다를 때 : ON)
SELECT EMP_ID, EMP_NAME, DEPT_ID, DEPT_TITLE
FROM EMPLOYEE
    JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID);


-- 사번, 사원 명, 직급코드, 직급명 조회(컬럼명이 같은 때 : USING)
SELECT EMP_ID, EMP_NAME, JOB_CODE, JOB_NAME
FROM EMPLOYEE
    JOIN JOB USING (JOB_CODE);
    
-- 부서명과 해당 부서의 지역 명 조회
-- 오라클 전용 구문
SELECT DEPT_TITLE, LOCAL_NAME
FROM DEPARTMENT, LOCATION
WHERE LOCAL_CODE = LOCATION_ID;
-- ANSI 표준 구문
SELECT DEPT_TITLE, LOCAL_NAME
FROM DEPARTMENT
    JOIN LOCATION ON (LOCAL_CODE = LOCATION_ID); 



-- 외부조인(OUTER JOIN) : 컬럼 값이 일치하지 않아도 조인에 포함
-- 어떤 테이블을 기준으로 잡을 것이냐
-- 사원명, 부서명 조회 (ANSI)
SELECT EMP_NAME, DEPT_TITLE
FROM EMPLOYEE
    JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID);

-- LEFT (OUTER) JOIN
SELECT EMP_NAME, DEPT_TITLE
FROM EMPLOYEE
    LEFT OUTER JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID);
 
-- 오라클 구문 : 기준이 아닌 컬럼에 +를 붙인다   
SELECT EMP_NAME, DEPT_TITLE
FROM EMPLOYEE, DEPARTMENT
WHERE DEPT_CODE = DEPT_ID(+);


-- RIGHT (OUTER) JOIN
SELECT EMP_NAME, DEPT_TITLE
FROM EMPLOYEE
    RIGHT OUTER JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID);
    
-- 오라클 구문 : 기준이 아닌 컬럼에 +를 붙인다   
SELECT EMP_NAME, DEPT_TITLE
FROM EMPLOYEE, DEPARTMENT
WHERE DEPT_CODE(+) = DEPT_ID;    

-- FULL (OUTER) JOIN
SELECT EMP_NAME, DEPT_TITLE
FROM EMPLOYEE
    FULL JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID);
    
-- 오라클 구문
SELECT EMP_NAME, DEPT_TITLE
FROM EMPLOYEE, DEPARTMENT
WHERE DEPT_CODE(+) = DEPT_ID(+);


-- 자체 조인(SELF JOIN)
-- 사번, 사원명, 부서코드, 관리자 사번, 관리자 이름
-- 오라클
SELECT E.EMP_ID, E.EMP_NAME, E.DEPT_CODE, E.MANAGER_ID, M.EMP_NAME 관리자이름
FROM EMPLOYEE E, EMPLOYEE M
WHERE M.EMP_ID = E.MANAGER_ID
ORDER BY MANAGER_ID;
-- ANSI
SELECT E.EMP_ID, E.EMP_NAME, E.DEPT_CODE, E.MANAGER_ID, M.EMP_NAME
FROM EMPLOYEE E
    JOIN EMPLOYEE M ON(M.EMP_ID = E.MANAGER_ID);


-- 다중 조인 (ANSI에서 조인할때는 조인 순서 중요)
-- 사번, 사원이름, 부서코드, 부서명, 부서 지역명
-- 오라클 전용
SELECT EMP_ID, EMP_NAME, DEPT_CODE, DEPT_TITLE, LOCAL_NAME
FROM EMPLOYEE, DEPARTMENT, LOCATION
WHERE DEPT_CODE = DEPT_ID 
    AND LOCATION_ID = LOCAL_CODE;
-- ANSI 표준
SELECT EMP_ID, EMP_NAME, DEPT_CODE, DEPT_TITLE, LOCAL_NAME
FROM EMPLOYEE
    JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
    JOIN LOCATION ON(LOCATION_ID = LOCAL_CODE);
    
-- 직급이 대리이면서 아시아 지역에 근무하는 직원의 사번, 이름, 직급명, 부서명,
-- 근무지역명, 급여 조회
-- 오라클
SELECT E.EMP_ID, E.EMP_NAME, J.JOB_NAME, DEPT_TITLE, LOCAL_NAME, SALARY
FROM EMPLOYEE E, JOB J, DEPARTMENT D, LOCATION L
WHERE E.JOB_CODE = J.JOB_CODE
AND DEPT_CODE = DEPT_ID
AND LOCATION_ID = LOCAL_CODE;
-- ANSI
SELECT EMP_ID, EMP_NAME, JOB_NAME, DEPT_TITLE, LOCAL_NAME, SALARY
FROM EMPLOYEE
    JOIN JOB USING(JOB_CODE)
    JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
    JOIN LOCATION ON(LOCATION_ID = LOCAL_CODE);
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    